### ISSUE TITLE
CLI, extensions problems

### ISSUE THREAD

**Issue by nlemoine** [bolt/bolt#2309]
Hi,

I've installed Bolt as a composer package but can't get the command line working. 
Neither the extensions in the admin area which triggers an error:
```
ErrorException thrown with message ""Symfony\Component\Console\Helper\DialogHelper" is deprecated since version 2.5 and will be removed in 3.0. Use "Symfony\Component\Console\Helper\QuestionHelper" instead."
```

Any ideas?

**Comment by bobdenotter** [comment]
Bump @rossriley

**Comment by rossriley** [comment]
Fixed with latest version of composer-install.

**Comment by nlemoine** [comment]
Thanks for the fix. 

However, the post install script still do nothing about the app dir. Shouldn't the config, database, cache, resources directories be created and filled with files accordingly ? 
When installing the web dir outside the root, there's still no command line utility (nut).
