### ISSUE TITLE
Update Frontend Controller to allow Accessing Content in after handler

### ISSUE THREAD

**Issue by CarsonF** [bolt/bolt#2579]
I want to be able to access the `Content` object in an after handler for the record route. This allows us to do backend tracking based on the content properties instead of parsing url/html/something-else-hacky.

I proposed setting in the request attributes:
```php
$app['request']->attributes->set('content', $content);
```
@rossriley pointed out this isn't the best spot for it. 

I agree and am looking for suggestions.
The only other place I can think is in `App`.

**Comment by bobdenotter** [comment]
Did we figure this one out yet? :-)

**Comment by rossriley** [comment]
My favourite idea was one that was mentioned before, instead of using straight up Symfony Responses we use our own BoltResponse object that contains the response in an object, that can be rendered in the normal way.

Only problem is, we currently return rendered html from the Controllers rather than a response, my preferred way would be for controllers to do:

    use Bolt\Response;

    .....
    public function controllerAction(Request $request)
    {
        //Do logic

        return new Response('path/to/template.twig', $context);
    }

The Bolt Response object could be identical to a normal Symfony response except that the rendering can be lazy and only happen on call to sendContent, at this point the Twig template can be rendered and that means that anything else can potentially modify the response context up until it's time to flush to the browser.

Obviously that means changing every controller response (and a major BC break for extensions / custom controllers)

We could patch it in more easily by overriding the current $app[twig']->render() and returning our new response from there, this would allow BC at the expense of an incorrect place to do this logic.

**Comment by CarsonF** [comment]
Yeah that was my original thought, and I agree is the best option. However, it is a major change. I was looking for a quick fix as a stop gap until this solution could be implemented. I'll just run a fork until that point. This might be something I work on for 2.2 as I'll be doing similar changes for namespacing twig folders.

**Comment by rossriley** [comment]
Fixed in #3191

**Comment by CarsonF** [comment]
@rossriley Not fixed. Frontend doesn't use BoltResponse yet.

**Comment by rossriley** [comment]
ah ok... reopen then.

**Comment by GawainLynch** [comment]
Implemented in the upcoming 2.3 controller refactoring branch.
