### ISSUE TITLE
Installation through composer breaks (no .htaccess and bolt-public not referenced)

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#3016]
When using `composer create-project bolt/composer-install <MYPROJECT> --prefer-dist` as per the website, there is some extra setup required (I selected 'no' to put Bolt in a different directory to webroot).

Firstly, there is no `.htaccess` file, so I just took that from another Bolt project manually and I went to the add initial users screen.

![image](https://cloud.githubusercontent.com/assets/3238878/6494054/de11fd40-c323-11e4-8d57-def8a18b5f5f.png)

Nothing works because all of the static files cannot be received. It's making requests to `app/view` instead of `bolt-public`. 

![image](https://cloud.githubusercontent.com/assets/3238878/6494074/08a5aef8-c324-11e4-8f26-0871a223893d.png)

Moving the contents of `bolt-public` to `app/view` fixes this problem.

They're simple fixes, but add an extra pain for automation and updates (especially that last one).

Tested on 2.0.6, going to ~~try master~~ ask someone else to try master because I can't Composer

**Comment by GawainLynch** [comment]
I totally blame the :koala:

**Comment by Pinpickle** [comment]
I just deployed one of these, where I moved bolt-public into app, and all of the requests are now being made to bolt-public (and aren't working, naturally).

I have no idea what is going on

**Comment by GawainLynch** [comment]
@Pinpickle I've merged @CarsonF's PRs from last night into master and release/2.1. Can you update/retry and see what is still b0rked for us.

**Comment by GawainLynch** [comment]
Closed by #3073 #3074

**Comment by timcooper** [comment]
I'm still seeing this issue, on a clean composer install with a separate public directory specified (`/public` for example's sake) no `.htaccess` file is being placed into `/public`. So visiting the site redirects to `/bolt/users/edit/` which 404s because it isn't being routed through `/public/index.php`

**Comment by melcarthus** [comment]
For me moving the contents from `bolt-public` to `app/view` did nothing. I did not even have an app/view to start with. Do I need an `htaccess` in the `public` folder? what should it contain?
