### ISSUE TITLE
Error when installing extension through the admin area

### ISSUE THREAD

**Issue by jaspernbrouwer** [bolt/bolt#3322]
__Reproducible steps__

- Sign in to Bolt (admin area).
- Go to "Extras" -> "View/install" Extensions.
- Enter an extension name ("bobdenotter/simone" in my case) and click "Browse Versions".
- Click "Install This Version" (the stable version (v1.0.0) in my case).

__Expected result__
- Not sure, but at least something like the extension being installed.

__Actual result__
- Nothing happens, the console shows the following error:

```txt
Fatal error:  Call to a member function getPackage() on a non-object in /path/to/src/Composer/Factory.php on line 198

{
  "error":{
    "type":"Whoops\\Exception\\ErrorException",
    "message":"Call to a member function getPackage() on a non-object",
    "file":"\/path\/to\/src\/Composer\/Factory.php",
    "line":198
  }
}
```

I'm running the latest version of Bolt (v2.1.5) and PHP v5.5.23 with OPcachev 7.0.4-dev.

**Comment by jaspernbrouwer** [comment]
Additionally, I've added the extension to `extensions/composer.json` manually (in a "require" option), but then clicking "Run update check" results in the following error:

```txt
Fatal error: Call to a member function getRepositoryManager() on a non-object in /path/to/src/Composer/Action/ShowPackage.php on line 71

{
  "error":{
    "type":"Whoops\\Exception\\ErrorException",
    "message":"Call to a member function getRepositoryManager() on a non-object",
    "file":"\/path\/to\/src\/Composer\/Action\/ShowPackage.php",
    "line":71
  }
}
```

**Comment by jaspernbrouwer** [comment]
Great, I seem to be hitting a `The process has been signaled with signal "11".`, these are always fun ;)

Looks like it's happening while the Symfony Process component is trying to execute `svn info --xml`.

**Comment by jaspernbrouwer** [comment]
So I recompiled PHP (yes, Gentoo) and Subversion, nothing's changed :(

The following exception is thrown:

```txt
Symfony\Component\Process\Exception\RuntimeException
"The process has been signaled with signal "11" (code 0) in file /path/to/vendor/symfony/process/Symfony/Component/Process/Process.php on line 369.

#0 /path/to/vendor/symfony/process/Symfony/Component/Process/Process.php(210): Symfony\Component\Process\Process->wait()
#1 /path/to/vendor/composer/composer/src/Composer/Util/ProcessExecutor.php(62): Symfony\Component\Process\Process->run(Array)
#2 /path/to/vendor/composer/composer/src/Composer/Package/Loader/RootPackageLoader.php(320): Composer\Util\ProcessExecutor->execute('svn info --xml', NULL)
#3 /path/to/vendor/composer/composer/src/Composer/Package/Loader/RootPackageLoader.php(188): Composer\Package\Loader\RootPackageLoader->guessSvnVersion(Array)
#4 /path/to/vendor/composer/composer/src/Composer/Package/Loader/RootPackageLoader.php(58): Composer\Package\Loader\RootPackageLoader->guessVersion(Array)
#5 /path/to/vendor/composer/composer/src/Composer/Factory.php(271): Composer\Package\Loader\RootPackageLoader->load(Array)
#6 /path/to/vendor/composer/composer/src/Composer/Factory.php(489): Composer\Factory->createComposer(Object(Composer\IO\BufferIO), '/path/to...', true)
#7 /path/to/src/Composer/Factory.php(75): Composer\Factory::create(Object(Composer\IO\BufferIO), '/path/to...', true)
#8 /path/to/src/Composer/PackageManager.php(180): Bolt\Composer\Factory->getComposer()
#9 /path/to/src/Composer/Action/ShowPackage.php(57): Bolt\Composer\PackageManager->getComposer()
#10 /path/to/src/Composer/PackageManager.php(331): Bolt\Composer\Action\ShowPackage->execute('installed', '', '', false)
#11 /path/to/src/Composer/PackageManager.php(380): Bolt\Composer\PackageManager->showPackage('installed')
#12 /path/to/src/Controllers/Extend.php(271): Bolt\Composer\PackageManager->getAllPackages()
#13 [internal function]: Bolt\Controllers\Extend->installed(Object(Bolt\Application), Object(Symfony\Component\HttpFoundation\Request))
#14 /path/to/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php(145): call_user_func_array(Array, Array)
#15 /path/to/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php(66): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#16 /path/to/vendor/silex/silex/src/Silex/Application.php(543): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#17 /path/to/vendor/silex/silex/src/Silex/Application.php(520): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request))
#18 /path/to/index.php(16): Silex\Application->run()
#19 {main}
```

Not sure where to continue...
I've read somewhere that the environment (like in `getenv()`) could cause some issues, so I guess I'll search there.

PS: Of course running `svn info --xml` in a console as the web-user works fine.

**Comment by jaspernbrouwer** [comment]
Can't find anything in the environment.

Running `sudo -u apache php -r "exec('svn info --xml', \$out); var_dump(\$out);"` doesn't segfault.

Next stop: using Symfony Process from the console...

**Comment by bobdenotter** [comment]
Hey Jasper, 

I did a quick test om my setup, and had no problems with this. That doesn't help you much, though.. 

Some other things to try: 

 - Have you tried another extension? Like Simpleforms, which is used a lot?
 - Does it work if you run `composer update --verbose` from the `extensions/` folder?

**Comment by jaspernbrouwer** [comment]
A manual composer update works fine, but afterwards the "View/install Extensions" still has the same problem.

I haven't tried locally yet, but I'm convinced the issue is specific to the Gentoo machine.

After some sleep, I realized that in theory it doesn't have to be a real segfault, but it could be that Symfony Process wrongly determines that. I'll look into that when I continue!

**Comment by ngroot** [comment]
@jaspernbrouwer this looks like a problem I had with my bolt extensions page. Can you take a look at
https://github.com/bolt/bolt/issues/3146

**Comment by GawainLynch** [comment]
@ngroot yep, thank you… I believe you're correct.

@jaspernbrouwer if you look in `extensions/composer.json` you will probably see `"require": []`.  If you do then deleting that file **or** changing that line to `"require": {}` should fix the problem.

**Comment by jaspernbrouwer** [comment]
I've already edited `extensions/composer.json` to contain:

```json
"require": {
    "bobdenotter/simone": "~1.0"
}
```

The issue remains.

**Comment by SahAssar** [comment]
@bobdenotter @GawainLynch Is this issue still around? I can't reproduce it.

**Comment by jaspernbrouwer** [comment]
This issue is specific to a Gentoo machine that I will no longer be using. Therefor I'll close this issue. No need to worry over an edge-case nobody uses :wink:

**Comment by SahAssar** [comment]
Ah, thanks @jaspernbrouwer :smile:
