### ISSUE TITLE
Status transition changes removing taxonomy

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#3868]
To reproduce:
* Listing page for 'Pages'
* 'Actions' drop down select a different status

**Comment by GawainLynch** [comment]
Related to #3908 and release/2.2 PR #3910

**Comment by simnom** [comment]
Is there a fix for this in the interim before 2.3? It's causing me a bit of grief :-\  Thanks!

**Comment by GawainLynch** [comment]
@simnom this should have been fixed in 2.2.8+ with #3910

**Comment by SahAssar** [comment]
Closing this as it should be fixed in #3910.

@simnom If you are still seeing this in current versions of bolt please reopen :)

**Comment by simnom** [comment]
Hey, will do.  Seeing some strange things when contenttypes have multiple taxonomies.  Trying to work out what's going on and will post back here or create a PR.

**Comment by simnom** [comment]
Hey @SahAssar, just been looking through this in more detail. I think that there's an issue if the contenttype has multiple taxonomies specifically in the `getIndexedTaxonomy` function, I would suggest that:

```php
$ret[] = $content->group['slug'] . '#' . $content->group['order'];
```
Will always return the first content taxonomy which then overwrites any subsequent taxonomy values that are set.

Looking to see if I can fix but this is my first look through the heavy lifting in Bolt so any suggestions would be welcome.

**Comment by SahAssar** [comment]
Alright, reopening, Perhaps @GawainLynch or @rossriley could shed som light on this?

**Comment by simnom** [comment]
Digging a bit deeper.....

I'm using multiple taxonomies on a contenttype and, rightly or wrongly, one of the defined taxonomies defines `grouping`.  At this point it always uses the initially set group.  Passing the `taxonomytype` through to `getIndexedTaxonomy` and checking for `grouping` seems to fix.  I'll create a PR for review.

**Comment by GawainLynch** [comment]
OK, the reason that this is open still is that we were able to address this problem in 2.2, but master was waiting on #4189 to be finished… submitted… and merged… due in about 5 minutes from now :grin:

**Comment by simnom** [comment]
5 minutes in a galaxy far far away? ;-)

**Comment by GawainLynch** [comment]
Hehe… that's the one

**Comment by SahAssar** [comment]
Fixed by #4188

**Comment by GawainLynch** [comment]
Still a problem in master… was planning on getting to this today…
