### ISSUE TITLE
Image upload via content type not working, creates JS error

### ISSUE THREAD

**Issue by stefantalen** [bolt/bolt#4539]
Bolt version: > 2.2.13 (2.2.14 too)
Browsers: Safari 9.0.1 + Google Chrome 46.0.2490.86

Content Type configuration:

```yml
projects:
    name: Projecten
    singular_name: Project
    slug: ons-werk
    singular_slug: ons-werk
    record_template: project.twig
    listing_template: projects.twig
    listing_sort: -datepublish
    #listing_records: 10
    fields:        
        title:
            label: Titel
            type: text
            group: Teksten
            required: true
        slug:
            type: slug
            uses: title
        activities:
            label: Werkzaamheden
            type: textarea
        method:
            label: Werkwijze
            type: textarea
        materials:
            label: Materialen
            type: textarea
        intro:
            label: Korte omschrijving
            type: textarea
            required: true
        description:
            label: Omschrijving
            type: markdown
        project_image:
            label: Algemene afbeelding
            type: image
            attrib: alt
            required: true
            group: Afbeeldingen
        images_before:
            label: Afbeeldingen "Voor"
            type: imagelist
        images_during:
            label: Afbeeldingen "Tijdens"
            type: imagelist
        images_after:
            label: Afbeeldingen "Na"
            type: imagelist
    relations:
        diensten:
            multiple: true
            label: Selecteer een of meerdere diensten
            order: id
            format: "{{ item.title }}"
```

When uploading an image for `images_before` the progress bar appears with the filename that should be uploaded but this JS error pops up and the file is never uploaded:

```txt
TypeError: (b.type||b.form.prop("method")||"").toUpperCase is not a function. (In '(b.type||b.form.prop("method")||"").toUpperCase()', '(b.type||b.form.prop("method")||"").toUpperCase' is undefined) _initFormSettings - lib.min.js:8312:305
```

The same goes when trying to upload a `project_image` but there is no progress bar shown.

**Comment by SahAssar** [comment]
I just have a few questions to help us locate the issue:

1. If you check the Network tab in the dev tools is the upload actually started? As in does it start the POST?
  * If so, what response does it receive?
2. Have you tried in incognito/no-extensions mode?
3. Is this on a newly updated site?

**Comment by stefantalen** [comment]
1. No XHR is being executed apart from the profiler toolbar
2. Tried it, failed too with the same JS error
3. Was notified of this issue two weeks ago, updated today to 2.2.14 to see it that would fix the problem but it didn't

**Comment by rossriley** [comment]
For some reason the problem is the presence of the field 'method' in your contenttype config.

Remove that field and it starts working.

I'm guessing it's a reserved word in one of the libraries we use.

**Comment by SahAssar** [comment]
Closing since this has been solved :)

Perhaps we should have a section in the docs with the reserved fieldnames though?

**Comment by stefantalen** [comment]
Using a different name doesn't really solve the problem, it is just a work-around to avoid the issue don't you agree? :wink:

Right now I'm to busy to figure out where this error occurs, but I'll try some debugging when I find the time.

**Comment by SahAssar** [comment]
Well, since it actually is a reserved fieldname it should show a warning that it is reserved and have the docs to back it up. But certain fieldnames *will* be reserved, and I don't think we will (realistically) get around that. For example if you name a field "datechanged" bolt will show you this warning: 

"In the contenttype for 'Page', the field 'datechanged' is defined, which is a reserved name. Please edit contenttypes.yml, and correct this."

So the question then becomes if it is reasonable that one of the reserved fieldnames is "method" (and of course that it should show the above warning), right?

Just trying to get to the bottom of what the issue "is" :)
