### ISSUE TITLE
Checkbox displays wrong value directly after saving, db = ok

### ISSUE THREAD

**Issue by anketwokings** [bolt/bolt#4997]
Hi, some odd behaviour with the checkbox in 2.2.19. This occurred after the fix in #4869

Steps to reproduce:
- In entry, checkbox is 0. 
- Set it to 1.
- Save the entry
- checkbox resets to 0 on screen. (but is correctly set to 1 in DB)
- reloading the page displays correct setting, 1.

(other way around is no problem:
- set from 1 to 0
- save
- still 0.
)

-------

 - Relevant Bolt Version: 2.2.19
 - browsers: chrome, FF

**Comment by bobdenotter** [comment]
Ping @rarila: My guess is that this is a quirk where the fields are 'reset' after saving. Could you look into this?

**Comment by rarila** [comment]
@bobdenotter will check that later. Just as a reminder changing that on [that line](https://github.com/bolt/bolt/blob/release/2.2/app/src/js/modules/editcontent.js#L304) from ``(item == "on")`` to ``item === '1'`` should fix that on 2.x.

v3 is another story…

**Comment by anketwokings** [comment]
Thanks! Fixed in 2.2.19-pl1, already put on clients website, and works like a charm. :)

**Comment by GawainLynch** [comment]
:+1:

**Comment by ToBe998** [comment]
Still broken in 2.2.19-pl1.

Reloading a page is now working, but just pressing "save" still does reset the checkbox.

**Comment by bobdenotter** [comment]
@ToBe998: Have you done a hard-refresh and/or cleared your browser's cache?

**Comment by ToBe998** [comment]
Tested in Chrome 49 even uncached.

1) Load page in editor
2) Check checkox
3) Press Save -> **Unchecked again - Error**
4) Reload page (or freshly open a page with a checked box -> Checked - Ok

**Comment by bobdenotter** [comment]
> "Unchecked again - Error" 

Error? What error does it give?

**Comment by ToBe998** [comment]
No sorry. The error i meant is "The checkbox state is unchecked but should be checked" .

**Comment by bobdenotter** [comment]
@ToBe998 I can't reproduce this..

My CT: 

```

dummies:
    name: Dummies
    singular_name: Dummy
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        check1:
            type: checkbox
        check2:
            type: checkbox
        check3:
            type: checkbox
        check4:
            type: checkbox
```

Setting them is reflected in the frontend.. for example: 

![screen shot 2016-04-25 at 17 02 37](https://cloud.githubusercontent.com/assets/1833361/14788312/9c622afa-0b07-11e6-99f6-9928376dc1d6.png)

![screen shot 2016-04-25 at 17 02 52](https://cloud.githubusercontent.com/assets/1833361/14788318/a06f60c2-0b07-11e6-8934-ae148e1bd273.png)

Then, changing them: (and saving, and reloading too)

![screen shot 2016-04-25 at 17 04 11](https://cloud.githubusercontent.com/assets/1833361/14788356/c3c9e8e4-0b07-11e6-8e75-cd3420626c1e.png)

![screen shot 2016-04-25 at 17 04 18](https://cloud.githubusercontent.com/assets/1833361/14788366/cd4473da-0b07-11e6-93bf-c54605964423.png)

**Comment by ToBe998** [comment]
The error happens when you click "Save" without reloading the page. The checkbox state is changed to "unchecked" but stored correctly. So a real page refresh shows the correct state, but just changing to "checked" and clicking "Save" changes it back to "unchecked".

**Comment by bobdenotter** [comment]
@ToBe998: Sorry mate, still can't reproduce. (or am not understanding you correctly..) See this short video: 

http://recordit.co/jTznOJZARX

**Comment by ToBe998** [comment]
Very strange. That video shows exactly my problem but works. I'll try to get more info for reproduction. But yes at this time, i cant see enough evidence to reopen this ticket. Damn! ;)

**Comment by ToBe998** [comment]
Short summary of my current state:
- I updated to 2.2.20
- added the contenttype exactly as shown above
- I completely replicate what is shown in the video
> Still same error. A click on save (not reloading the page) sets all checkboxes to "unchecked" no matter what state they had on last reload.

**Comment by bobdenotter** [comment]
@ToBe998 I did some more testing, on MySQL and PHP 5.3 and 5.6, and in all cases it works as expected. So, i still cannot reproduce the issue you're having.

**Comment by ToBe998** [comment]
@bobdenotter can you give me some hints on the javascript function that executes the ajax request on save and the part that set's checkbox states. Maybe i can debug that issue myself then and hopefully provide some more insights.

**Comment by rossgardt** [comment]
The logic that is being applied in [editcontent.js:298](https://github.com/bolt/bolt/blob/release/2.2/app/src/js/modules/editcontent.js#L298) is perfectly fine.

The problem is that if the [bolt.min.js|https://github.com/bolt/bolt/blob/release/2.2/app/view/js/bolt.min.js] is being updated, **you will need to copy that** file to you `./public/bolt-public/view/js` folder.

@bobdenotter What is the intended workflow to keep those two folders in sync?

Best,
Benedikt

**Comment by SahAssar** [comment]
@rossgardt: IIRC those files should be auto-copied/updated when updating bolt... But as @bobdenotter is on vacation ( :smile: ) the real explanation might take a little while unless someone else has a good explanation?

**Comment by GawainLynch** [comment]
That is correct, @SahAssar. When Bolt detects a version change it will sync the `view/` directory if it doesn't match Bolt's git path.

If you install via-archive or `composer install-project` they should be present.

**Comment by ToBe998** [comment]
The project was originally installed via `composer require` but did not update anything after a much later `composer update`. Maybe some script hook inside the composer.json is missing?

**Comment by GawainLynch** [comment]
Ah, cool. OK, well this is the ["magic" required](https://github.com/bolt/composer-install/blob/master/composer.json#L13-L25) in the root `composer.json file`:

```json
    "scripts": {
        "post-install-cmd": [
            "Bolt\\Composer\\ScriptHandler::installAssets"
        ],
        "post-update-cmd": [
            "Bolt\\Composer\\ScriptHandler::installAssets"
        ],
        "post-create-project-cmd": [
            "Bolt\\Composer\\ScriptHandler::configureProject",
            "Bolt\\Composer\\ScriptHandler::installThemesAndFiles",
            "nut extensions:setup"
        ]
    },
```

**Comment by ToBe998** [comment]
This seems to be the problem for our Bolt 3 instances, but it looks like the bolt2 composer.json does not provide such a hook, right?

This is same file in the [bolt 2.2 repo](https://github.com/bolt/composer-install/blob/release/2.2/composer.json):
```
    "scripts": {
        "post-create-project-cmd": [
            "Bolt\\Composer\\ScriptHandler::bootstrap"
        ]
    },
```

**Comment by GawainLynch** [comment]
That is correct. It was added in 3.0-dev to try and get the behaviour consistent and predictable across all install types.

**Comment by GawainLynch** [comment]
PRed and update to docs https://github.com/bolt/docs/pull/430
