### ISSUE TITLE
Successful ajax save doesn't update the save date

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#5193]
When i press "save" in contentedit, it waits, then i see that response is ok, data is updated. But time is still "saved 29 minutes ago"
![2016-04-16 02-35-48](https://cloud.githubusercontent.com/assets/2145313/14574244/40b2b91e-037c-11e6-9222-56f7d60a77fd.png)

**Comment by SahAssar** [comment]
@Boorj Just checking in, I had a similar problem under 2.2, which was because of proxy caching at sitegrounds. Is this still an issue for you? Did you find out why you had the issue?

I'm asking since our problem was similar and was due to overly aggressive caching by the intermediary (and also since it's an old issue that has not been re-reported since it was opened).

**Comment by SahAssar** [comment]
Because of no reply and a similar problem fixed in #4741 I'm going to assume this can be closed... Please reopen/comment if I'm wrong!

**Comment by Boorj** [comment]
@SahAssar that was ok for me, sorry, for not answering.. :blush: Seems that now it works ok.
And, by the way, it is still not enough clear to understand :arrow_right:  #5010
