### ISSUE TITLE
custom fields not working in repeater field, bug? 

### ISSUE THREAD

**Issue by serweb-labs** [bolt/bolt#5403]
1. **Bug summary**: I am using the "https://github.com/bolt/bolt-extension-starter-extended" example, where a custom field called "examplefield", is created but I can not work with a field of type
"repeater", to save does not return any error (the field is ignored), and if you added the "name" attribute with the name of `repeat-field-name[index][fieldname-in-repeat],` in this case" `repeater [0] [bikeken] `"by submitting the form, it returns an error" unknown column "

**Expected result**: Save field :smile: 

 **Actual result**:
 By Default: 
To save does not return any error (the field is ignored)
Forcing repeat-field-name[index][fieldname-in-repeat]
If you added the "name" attribute with the name of `repeat-field-name[index][fieldname-in-repeat],` in this case" `repeater [0] [bikeken] `"by submitting the form, it returns an error" unknown column "
**Screenshots**: 
![captura de pantalla_2016-06-03_00-17-01](https://cloud.githubusercontent.com/assets/6233822/15768245/8b1619dc-2925-11e6-9052-e99d2c69db3d.png)
![captura de pantalla_2016-06-03_00-16-49](https://cloud.githubusercontent.com/assets/6233822/15768246/8b166248-2925-11e6-9d5e-c73d5f6686ba.png)

Reproduction
------------
**Steps to reproduce**: 
 - Create an extension that adds a custom field, based on the package "https://github.com/bolt/bolt-extension-starter-extended" start, make sure it is installed from the "extensions" on the backend of Bolt.
-  Add the field to a content type, section repeater (eg using the content type showcase).
-  In our content type, add a new entry, and fill our field in the repeater field.
-  Click on "save" button.

-------

 - Relevant Bolt Version:  3.0.3
 - Install type:Composer install 
 - PHP version:  5.6?
 - Used webserver: php built-in

**Comment by SahAssar** [comment]
Just to clarify, this happens even if that extension  is not installed, only with a slightly different error message:
```
{"error":{"type":"Doctrine\\DBAL\\DBALException","message":"Unknown column type \"repeater\" requested. Any Doctrine type that you use has to be registered with \\Doctrine\\DBAL\\Types\\Type::addType(). You can get a list of all the known types with \\Doctrine\\DBAL\\Types\\Type::getTypesMap(). If this error occurs during database introspection then you might have forgot to register all database types for a Doctrine Type. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty you might have a problem with the cache or forgot some mapping information.","file":"\/var\/www\/2\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php","line":228}}
```

**Comment by rossriley** [comment]
Fixed in #5684 and shipped in the 3.1 release.

**Comment by IntellectProductions** [comment]
I'm still getting this issue with version 3.2.. I am doing a {{ dump(context) }} and my first two fields show, but my custom field will not... although I am setting a value in it.

```
color_swatches:
    type: repeater
    label: Color Swatches
    fields:
        title:
            type: text
        number:
            type: integer
        hexcode:
            type: colorpicker
            label: Hex Code
```

The hexcode property is not showing, but the other two do. The extension and custom field work perfectly fine and as expected. It just won't persist the value or even show the property inside the repeater field.
