### ISSUE TITLE
[BUG] repeater field // HTML editor // shows up twice

### ISSUE THREAD

**Issue by steiha** [bolt/bolt#5427]
Details
-------

 - Relevant Bolt Version: [ 2.2 | 3.0 | master ]
 - Install type: Composer install
 - PHP version: 5.5
 - Used webserver: Apache
 - For UX/UI issues: Chrome/ Safari (OS X 10.11.5)

Reproduction
------------

- vanilla install via composer

`composer create-project bolt/composer-install:^3.0 bolt --prefer-dist`

- add a new content type

>         example:
            name: Examples
            singular_name: Example
            fields:
                list:
                    type: repeater
                    limit: 10
                    fields:
                        list_title:
                            type: text
                        list_content:
                            type: html

- create a new example
- add some content
- save record
- leave edit view, click somewhere else
- open this record again
- html editor shows up twice

<img width="786" alt="bolt-editor-twice" src="https://cloud.githubusercontent.com/assets/2902528/15940657/4c2054f6-2e7d-11e6-9a87-dbe15b267bde.png">

**Comment by rossriley** [comment]
Fixed by #5436

**Comment by saltpeanuts** [comment]
Still seeing this issue. Triggers exactly as described if I have more than one repeater set. 

## Reproduction

- Define a content type with repeater set as outlined by steiha above
- Add first repeater set to record
- Hit save
- Leave edit view (go back to dashboard)
- Open record again, everything fine, no duplicate.
- Add a second repeater set using the 'Add New Repeater Set' button
- Hit save
- Leave edit view (go back to dashboard)
- Open record again, html box and content is duplicated in both repeater sets

Firefox 47 / Chrome 51 (Win 7 & Linux Mint)

**Comment by dantleech** [comment]
Same here with version 3.0.7, as reported in #5469

**Comment by SahAssar** [comment]
Btw, since I closed #5469 as it is a dupe of this I'll ask here: Since #5526 (released in v3.0.10) I can't reproduce this, could I just get a verification that it works from one of you guys?

**Comment by saltpeanuts** [comment]
Only had chance to give it a quick test but so far it's looking fixed here on 3.0.11. Thanks!

**Comment by SahAssar** [comment]
@saltpeanuts Thanks for verifying! Lemme know if there are any issues and we/I will look into them!

**Comment by saltpeanuts** [comment]
@SahAssar  No problem, just tested with a markdown field as well, which is also working, so looks like #5489 is fixed too. 

(although I did notice a separate issue with markdown content being lost when using Duplicate Set with a markdown field, I can open this as a new issue if it's not already open somewhere)

**Comment by SahAssar** [comment]
@saltpeanuts I think that is the same problem as #5476, so hopefully it will be fixed in the same sweep. :)

**Comment by saltpeanuts** [comment]
Duh, thought it seemed vaguely familiar :/ It's well past wine 'o clock :)
