### ISSUE TITLE
[BUG] Using singular_slug as key in contenttypes.yml breaks saving content

### ISSUE THREAD

**Issue by ToBe998** [bolt/bolt#5981]
If you use a contenttype that has the singular_slug as it's key, saving the content (ajax call) returns an error.

```
Uncaught Exception: InvalidRepositoryException
Attempted to load repository for invalid class or alias: articles. Check that the class, alias or contenttype definition is correct.

Bolt InvalidRepositoryException in EntityManager.php line 259: Attempted to load repository for invalid class or alias: articles. Check that the class, alias or contenttype definition is correct.
```

This is my complete contenttypes.yml
```
article:
    slug: articles
    singular_slug: article
    fields:
        title:
            type: text
            class: large
            group: content
            required: true
        kicker:
            type: text
        intro:
            type: textarea
```
If you change the key from `article`to `articles`, the error is gone.

Details
-------

 - Relevant Bolt Version: 3.2.0-rc2
 - Install type: Composer
 - PHP version: 5.5
 - Used web server: Apache 2.4
 - For UX/UI issues: Chrome

Reproduction
------------

See sample contenttypes.yml above.
- On Overview add some samples with lorem ipsum generator
- Open an article
- Press Save
The loading spinner keeps loading and the response of the ajax request (as seen in the web-dev tools of your choice) show the mentioned exception page.

**Comment by bobdenotter** [comment]
Pinging @rossriley Could you take a look at this? I assume it's related to #5971

**Comment by GawainLynch** [comment]
Fixed in #5987

**Comment by phpetra** [comment]
I'm sorry to say but this did not fix my issues. I created a new issue : #6007
