### ISSUE TITLE
Repeater field problem

### ISSUE THREAD

**Issue by dslacey** [bolt/bolt#6888]
Description: Repeater fields don't display in Showcases in the default Bolt 3.2.16 Base-2016 theme. 

 - Bolt Version: 3.2.16 
 - Install type: Zip  install 
 - PHP version: 5.6
 - Used web server: Local server running on MAMP with Apache, MySQL 

The Bolt dashboard includes an option to add a new Showcase and the Showcase edit form includes a Repeater tab to add Repeater sets, each with a title, image and formatted text/html. But when I followed this process and added a new Showcase with Repeater sets, the content added using the Repeater tab did not display in the Showcase when viewed on the site. Having created the repeater content I expected it to show up on the site. Instead only the Showcase title and description were displayed.

After determining that there didn't seem to be any obvious reason why the Repeaters were not displaying, I spent some time getting to know Bolt and its components and finally determined there was a problem with the value of the fieldtype that is set in one of the Twig templates in the Base-2016 theme folder:

partials/_sub_fields.twig, lines 75 & 76:

`{% set fieldtype = repeaterfield.fieldtype() %}`

Debugging with `{% dump(fieldtype) %}` revealed that fieldtype set this way always returned NULL, rather than one of the expected fieldtypes: text, image, or html. The subsequent code is set up to process only those repeaters that have the expected fieldtypes and to ignore all others, and as a result none of the repeaters was being processed or displayed. 

Note: there are no error messages displayed. Someone viewing the Showcase would not have any idea that the repeater content was missing.

Reproduction

- Install Bolt 3.2.16 with the theme set to Base-2016 (default).
- Login and add a new Showcase, with a title and a description, then select the Repeater tab and add a new Repeater set with content in each of the fields: Repeattitle, Repeatimage, and Repeatcontent.
- Save the Showcase.
- View the site (repeater fields cannot be previewed) and select the Showcase you just created.
- Check whether any of the Repeater content that you added to the Showcase displays.

**Comment by SahAssar** [comment]
Hmm, I might be wrong but I think this is one of the things that were fixed in 3.3, could you try upgrading?

**Comment by dslacey** [comment]
It still does not work in 3.3.1. My understanding is that no changes could be made until a new issue was submitted.

**Comment by GawainLynch** [comment]
> My understanding is that no changes could be made until a new issue was submitted.

Yeah, zero stress. There were a series of subtle bugs around this that we were chasing in 3.2.15, 3.2.16 & 3.2.17 that should have been resolved in 3.3.x hence the suggestion.

**Comment by bobdenotter** [comment]
In Bolt 3.3 there's a new way of using "fields", as you can see in the themes: 

https://github.com/bolt/themes/blob/master/base-2016/record.twig#L10

These don't rely on macro's, nor the deprecated `fields()` twig function. 

The usage is slightly different, though. To include Repeaters in this, it's best practice to use the scoped `with`: 

```
    {% with { 'record': record, 'common': true, 'extended': true, 'repeaters': true } %}
        {{ block('sub_fields', 'partials/_sub_fields.twig') }}
    {% endwith %}
```

I'll make a PR to do this by default in the base-2016 and skeleton themes.
