### ISSUE TITLE
[3.4b4] Named repeaters are not saved even if empty

### ISSUE THREAD

**Issue by xiaohutai** [bolt/bolt#7116]
Named repeaters don't get saved if the fields are empty. I think assigning a block is sufficient to have it saved, even if empty.
  - For example, a block with (only) an unchecked checkbox would never get saved, or in case of bunch of optional fields (but you still want the info that there is a block of a certain type)
  - The `default` setting does not work (e.g. to pre-fill a type field), but that might be a separate issue/feature.

**Comment by GawainLynch** [comment]
Fixed in #7117 by Team Ninja

**Comment by xiaohutai** [comment]
Thanks both of you for this quick fix 👍

**Comment by xiaohutai** [comment]
Still not fixed.

See also: https://github.com/bolt/bolt/pull/7117#issuecomment-340471629

Not sure if I need to open a separate issue for the `default` value.

**Comment by GawainLynch** [comment]
It went in *after* beta 5 and WFM … could you please test on 3.4-HEAD

**Comment by bobdenotter** [comment]
@GawainLynch According to this, it should be in the b5, right? https://github.com/bolt/bolt/commits/3.4

**Comment by GawainLynch** [comment]
@bobdenotter according to [this](https://github.com/bolt/bolt/issues/7116#issuecomment-340480800) I can't read … if anyone needs me, I'm hiding in the Stupid Corner … AGAIN! :wink:

**Comment by bobdenotter** [comment]
Is this still an issue, @xiaohutai ? I think it works correctly for me, now.

**Comment by xiaohutai** [comment]
@bobdenotter still not working for me on Bolt 3.4.2

**Comment by xiaohutai** [comment]
Ping @rossriley
Not to pressure, but to make sure it doesn't get lost :)

**Comment by ldaguise** [comment]
I experience this issue too.
👍

**Comment by rossriley** [comment]
I'll check this out, looks like we have a regression somewhere
