### ISSUE TITLE
Content type field level validation issue

### ISSUE THREAD

**Issue by thematicmi** [bolt/bolt#7731]
When adding required=true to a field within a repeater, the error message reported (error summary) is missing the field label

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 3.5.7
| Install type                   |  Composer install
| BC Break                     | yes/no
| PHP version                 | 7.2
| Web server                  | Apache
| For UX/UI issues        | Firefox/Chrome

Reproduction
------------

Simply having required=true on a field within a repeater will reproduce this (minor) issue

### Bug summary

The error summary produced under the above scenario is:

Field “”: Is required or needs to match a pattern!

I assume this is because the field <label> tags within a repeater do not have the "for" attribute

### Steps to reproduce

Have a contenttype with a repeater and at least one field
Set the field to include the property required: true
Attempt to author the new [contenttype] within Bolt's admin and leave the field blank
Note error summary

### Expected result

Field “FIELD NAME HERE”: Is required or needs to match a pattern!

### Actual result

Field “”: Is required or needs to match a pattern!

Appreciate this is minor/cosmetic, but if the fields are on different tabs it's difficult for end users to immediately see what they've missed

**Comment by thematicmi** [comment]
![7731](https://user-images.githubusercontent.com/3592421/51244164-4a052100-197c-11e9-8407-a9fcd46ab200.png)

**Comment by rossriley** [comment]
I think this one has already been addressed in 3.6.* when we fixed quite a few bugs relating to repeaters working correctly with required and default values.

**Comment by thematicmi** [comment]
It's still a problem in Bolt 3.6.3 - specifically the error summary. This can be fixed by making sure all <label> tags have a "for" attribute (tested on 3.6.3 by editing the markup directly)

**Comment by rossriley** [comment]
ok, let me double check this and see if there's anything more to do.
